// all news
export const ALL_NEWS_START = "ALL_NEWS_START"
export const ALL_NEWS_SUCCESS = "ALL_NEWS_SUCCESS"
export const ALL_NEWS_ERROR = "ALL_NEWS_ERROR"

// category wise news
export const CATEGORY_WISE_NEWS_START = "CATEGORY_WISE_NEWS_START"
export const CATEGORY_WISE_NEWS_SUCCESS = "CATEGORY_WISE_NEWS_SUCCESS"
export const CATEGORY_WISE_NEWS_ERROR = "CATEGORY_WISE_NEWS_ERROR"